#!/bin/sh
set -e

# $1: "upgrade" "remove" "purge"
# $2: versione
case "$1" in
	purge)
		rm /usr/local/etc/domopi/*
		;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
